name: Build docker image and push to Harbor
on:
  push:
    tags:
      - '*'
    paths-ignore:
      - "k8s/**"
      - '**/*.md'

jobs:
  Built-login-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and push image
        run: |-
          GIT_COMMIT=$(git rev-parse HEAD)
          GIT_TAG=$(git describe --tags --exact-match --abbrev=0 2>/dev/null || echo $(git describe --tags $(git rev-list --tags --max-count=1))-dev)

          IMAGE_TAG="harbor.whalebone.io/whalebone/${{ github.event.repository.name }}:$GIT_TAG"
          IMAGE_TAG=$(echo $IMAGE_TAG | tr '[A-Z]' '[a-z]')
          
          docker build . --file Dockerfile --tag "$IMAGE_TAG" --build-arg GH_USERNAME=${{ secrets.GH_USERNAME }} --build-arg GH_TOKEN=${{ secrets.GH_TOKEN }} --build-arg GIT_COMMIT="$GIT_COMMIT" --build-arg VERSION="$GIT_TAG"

          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login harbor.whalebone.io/whalebone -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push "$IMAGE_TAG"
